name: flutter_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.7.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
